site_name: Developing with RingCentral
site_url: https://github.com/ringcentral/ringcentral-api-docs
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-docs
edit_uri: tree/master/docs
docs_dir: docs

plugins:
  - git-committers:
      repository: ringcentral/ringcentral-api-docs
      branch: master
  - bootstrap-tables
  - ringcentral-api-index:
      outfile: basics/api-index.md

theme:
  name: ringcentral
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.superfences
  - codehilite:
      linenums: "None"
  - mdx_include

extra_css:
- extra.css
- css/mega-menu.css

copyright: "1999-2020 RingCentral, Inc. All rights reserved."

google_analytics: ['UA-57519112-1', 'developers.ringcentral.com']

pages:

# ---- CORE APIs ----
- 'Primary':
  - 'Voice':
    - 'Overview': 'voice/index.md'
    - 'Getting Started': 'voice/quick-start.md'
    - 'Placing Calls':
      - 'RingOut': 'voice/ringout.md'
      - 'WebRTC': 'voice/webrtc.md'
      - 'URI Scheme': 'voice/uri-scheme.md'
    - 'Call Routing':
      - 'Overview': 'voice/call-routing/index.md'
      - 'Get Started': 'voice/call-routing/get-started.md'
      - 'Answering Rules Overview': 'voice/call-routing/manual/answering-rules.md'
      - 'User Answering Rules': 'voice/call-routing/manual/user-answering-rules.md'
      - 'Company Answering Rules': 'voice/call-routing/manual/company-answering-rules.md'
      - 'Call Queues': 'voice/call-routing/manual/call-queues.md'
      - 'Call Queues Presence': 'voice/call-routing/manual/call-queues-presence.md'
      - 'Call Forwarding/Flipping': 'voice/call-routing/manual/call-forwarding.md'
    - 'Call Control':
      - 'Overview': 'voice/call-control.md'
      - 'Finding active calls': 'voice/finding-active-calls.md'
      - 'Detecting state changes': 'voice/call-control-sessions.md'
      - 'Pre-call Control': 'voice/pre-call-control.md'
      - 'Active-call Control': 'voice/active-call-control.md'
      - 'Call Monitoring': 'voice/supervision.md'
      - 'Conference call': 'voice/conference.md'
      - 'Warm Transfer': 'voice/warm-transfer.md'
      - 'Telephony Session Notifications': 'voice/telephony-session-notifications.md'
      - 'Call Control SDK': 'https://github.com/ringcentral/ringcentral-call-control-js'
    - 'Call Logs':
      - 'Reading Call Log Data': 'voice/call-log/reading-call-log.md'
      - 'Data Types': 'voice/call-log/api.md'
      - 'Detailed Call Log Data': 'voice/call-log/details.md'
      - 'Data Archival': 'voice/call-log/archival.md'
      - 'Call Recordings': 'voice/call-log/recordings.md'
      - 'Synchronization': 'voice/call-log/sync.md'
      - 'Best Practices': 'voice/call-log/best-practices.md'
      - 'Access Control': 'voice/call-log/access.md'
    - 'Call Analytics':
      - 'Calculating Call Metrics': 'voice/calculating-call-time-metrics.md'
    - 'Sample Applications':
      - 'Building a Web Phone with WebRTC': 'https://ringcentral-tutorials.github.io/getting-started-with-webrtc-js-demo/'
      - 'Call Log Analytics for iOS': 'https://ringcentral-tutorials.github.io/calllog-analytics-swift-demo/'
      - 'Call Log Visualizations': 'https://ringcentral-tutorials.github.io/calllog-visualization-nodejs-demo/'
      - 'Call Recording Push Notification': 'https://ringcentral-tutorials.github.io/callrecording-notification-node/'
  - 'SMS and Fax':
    - 'Overview': 'messaging/index.md'
    - 'Getting Started': 'messaging/quick-start.md'
    - 'Standard SMS':
      - 'Best Practices': 'messaging/sms/best-practices.md'
      - 'Sending an SMS': 'messaging/sms/sending-sms.md'
      - 'Sending an MMS': 'messaging/sms/sending-images.md'
      - 'Valid SMS Numbers': 'messaging/sms/valid-sms-numbers.md'
    - 'High Volume SMS':
      - 'Overview': 'messaging/sms/high-volume/index.md'
      - 'Best Practices': 'messaging/sms/high-volume/best-practices.md'
      - 'Sending High Volume SMS': 'messaging/sms/high-volume/sending-highvolume-sms.md'
      - 'Reading High Volume Message Store': 'messaging/sms/high-volume/message-store.md'
      - 'Toll-Free vs. Local Numbers': 'messaging/sms/high-volume/toll-free-sms-vs-local-numbers.md'
      - 'Opt-in / Opt-out': 'messaging/sms/high-volume/opt-out.md'
      - 'Event Notifications': 'messaging/sms/high-volume/events.md'
      - 'Errors Handling': 'messaging/sms/high-volume/handling-errors.md'
    - 'Fax':
      - 'Sending Faxes': 'messaging/fax/sending-faxes.md'
      - 'Multipart Formats': 'messaging/fax/fax-multipart-formats.md'
      - 'Receiving Faxes': 'messaging/fax/receiving-faxes.md'
      - 'Forwarding and Resending Faxes': 'messaging/fax/resending-faxes.md'
    - 'Pager Messages':
      - 'Sending Pager Messages': 'messaging/pager/sending-pager-messages.md'
    - 'Message Store':
      - 'Sending Messages': 'messaging/message-store/messaging.md'
      - 'Working with Message Store': 'messaging/message-store/working-with-message-store.md'
      - 'Message Synchronization': 'messaging/message-store/message-sync.md'
      - 'Modifying Message Histories': 'messaging/message-store/message-histories.md'
      - 'Message Store Export': 'messaging/message-store/message-exports-report.md'
    - 'Sample Applications':
      - 'SMS Sample App Walkthrough': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-demo/'
      - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'
      - 'Two-factor Authentication': 'https://ringcentral-tutorials.github.io/sms-2fa-nodejs-demo/'
      - 'Custom Fax Cover Pages': 'https://ringcentral-tutorials.github.io/fax-cover-page-nodejs-demo/'

  - 'Team Messaging':
    - 'Overview': 'team-messaging/index.md'
    - 'Getting Started': 'team-messaging/quick-start.md'
    - 'Posting Messages':
      - 'Simple text messages': 'team-messaging/manual/posting.md'
      - 'Posting Cards': 'team-messaging/manual/posting-cards.md'
      - 'Posting Images': 'team-messaging/manual/posting-images.md'
      - 'Uploading and posting files': 'team-messaging/manual/attaching-files.md'
    - 'Chats, Groups, Teams':
      - 'Chats': 'team-messaging/manual/chats.md'
      - 'Conversations': 'team-messaging/manual/conversations.md'
      - 'Teams': 'team-messaging/manual/teams.md'
      - 'Pagination': 'team-messaging/manual/pagination.md'
    - 'Incoming Webhooks':
      - 'Webhook Creation': 'team-messaging/manual/webhook-creation.md'
      - 'Webhook Posting (v2)': 'team-messaging/manual/webhook-posting.md'
      - 'Webhook Posting (v1)': 'team-messaging/manual/formatting.md'
      - 'Testing using cURL': 'team-messaging/manual/testing-webhooks.md'
    - 'Compliance Export':
      - 'Compliance Export': 'team-messaging/manual/compliance-export.md'
      - 'Export File Structure': 'team-messaging/manual/compliance-export-structure.md'
    - 'Bots':
      - 'Building a Bot Locally': 'team-messaging/manual/local-bots.md'
      - 'Build a Bot in Node': 'team-messaging/manual/node.md'
      - 'Bot Frameworks': 'team-messaging/manual/frameworks.md'
    - 'Outgoing Events and Webhooks':
      - 'Subscribing to Webhooks': 'team-messaging/manual/outgoing-webhooks.md'
      - 'Post Events': 'team-messaging/manual/events-posts.md'
      - 'Chat Events': 'team-messaging/manual/events-groups.md'
      - 'Incoming Webhook Events': 'team-messaging/manual/events-incoming-webhooks.md'
    - 'Deep links': 'team-messaging/manual/links.md'
    - 'Sample Applications':
      - 'Bot using IBM Watson and Botkit': 'https://ringcentral-tutorials.github.io/botkit-watson-bot-nodejs-demo/'
      - 'Voicemail Transcription Bot': 'https://ringcentral-tutorials.github.io/ringcentral-ai-bot/'

  - 'Meetings':
    - 'Overview': 'meetings/index.md'
    - 'Getting Started': 'meetings/quick-start.md'
    - 'RingCentral Video API': 'meetings/video.md'
    - 'Embeddable': 'meetings/embeddable.md'

  - 'Analytics (Beta)':
    - 'Overview': 'analytics/index.md'
    - 'Getting Started': 'analytics/quick-start.md'
    - 'Call Performance Reports':
      - 'Data Guide': 'analytics/call-performance/index.md'
      - 'API Usage Information': 'analytics/call-performance/api-reference.md'
      - 'API Reference' : 'https://ringcentral-call-performance.readthedocs-hosted.com/en/latest/swagger-api-ref/'
      - 'Sample Application': 'https://github.com/ringcentral/call-performance-api-demo'
    - 'Troubleshooting Guide': 'analytics/troubleshooting.md'
    - 'Changelog': 'analytics/changelog.md'

  # ---- SECONDARY APIs ----
- 'Secondary':

  - 'Using the API':
      - 'Methods, endpoints and parameters': 'basics/uris.md'
      - 'Exploring the API': 'basics/explorer.md'
      - 'Using phones in sandbox': 'basics/your-rc-phone.md'
      - 'Media content': 'basics/media.md'
      - 'App permissions': 'basics/permissions.md'
      - 'URI schemes': 'basics/uri-schemes.md'
      - 'Rate limits': 'basics/rate-limits.md'
      - 'API Change Log':
        - 'Preface': 'basics/changelog/index.md'
        - 'v.1.0.47 (May 2021)': 'basics/changelog/1_0_47.md'
        - 'v.1.0.46 (Feb 2021)': 'basics/changelog/1_0_46.md'
        - 'v.1.0.45 (Nov 2020)': 'basics/changelog/1_0_45.md'
        - 'v.1.0.44 (Aug 2020)': 'basics/changelog/1_0_44.md'
        - 'v.1.0.43 (May 2020)': 'basics/changelog/1_0_43.md'
        - 'v.1.0.42 (Feb 2020)': 'basics/changelog/1_0_42.md'
        - 'v.1.0.41 (Dec 2019)': 'basics/changelog/1_0_41.md'
        - 'v.1.0.40 (Aug 2019)': 'basics/changelog/1_0_40.md'
        - 'v.1.0.39 (May 2019)': 'basics/changelog/1_0_39.md'
      - 'API Quick Reference': 'basics/api-index.md'

  - 'Applications':
      - 'Development Lifecycle':
          - 'Tips for your first app': 'basics/your-first-steps.md'
          - 'Create an application': 'basics/create-app.md'
          - 'Develop in sandbox': 'basics/sandbox.md'
          - 'Graduate to production': 'basics/production.md'
      - 'App Promotion':
          - 'Submit to the App Gallery': 'basics/app-gallery.md'
          - 'Update a Profile': 'basics/update-profile.md'
          - 'Checklist and Best Practices': 'basics/app-gallery-checklist.md'
      - 'Application Management':
          - 'Using Lead Forms': 'basics/lead-forms.md'
          - 'Install App Buttons': 'basics/install-app-button.md'
      - 'Partner Ecosystem':
          - 'Overview': 'basics/partner-compatibility.md'
          - 'Technical Requirements': 'basics/partners/segregated-environments.md'
          - 'Brand Guidelines':
             - 'AT&T Office@Hand': 'basics/partners/att.md'
             - 'Avaya Cloud Office': 'basics/partners/aco.md'
             - 'BT Cloud Work': 'basics/partners/bt.md'
             - 'Rainbow Office': 'basics/partners/alcatel.md'
             - 'TELUS Business Connect': 'basics/partners/telus.md'
             - 'Unify Office': 'basics/partners/atos.md'
  - 'Account':
    - 'Overview': 'account/index.md'
    - 'Users and Extensions': 'account/extensions.md'
    - 'Phone Numbers': 'account/phone-numbers.md'
    - 'Call Forwarding/Flipping': 'account/call-forwarding-flipping.md'
    - 'User Feature Flags': 'account/feature-flags.md'
    - 'Custom Fields': 'account/custom-fields.md'
    - 'Presence': 'account/presence.md'

  - 'Authentication':
    - 'Overview': 'authentication/index.md'
    - 'Getting Started': 'authentication/quick-start.md'
    - 'Developer Manual':
      - 'Auth code flow': 'authentication/auth-code-flow.md'
      - 'Auth code flow with PKCE': 'authentication/auth-code-pkce-flow.md'
      - 'Password flow': 'authentication/password-flow.md'
      - 'Implicit grant flow': 'authentication/implicit-grant-flow.md'
      - 'Using auth tokens': 'authentication/tokens.md'

  - 'Address Book':
    - 'Overview': 'address-book/index.md'

  - 'Notifications and Events':
    - 'Overview': 'notifications/index.md'
    - 'Push Notifications':
      - 'Getting Started': 'notifications/push-notifications/quick-start.md'
      - 'Using PubNub': 'notifications/push-notifications/pubnub.md'
    - 'WebHooks':
      - 'Getting Started': 'notifications/webhooks/quick-start.md'
      - 'Creating Webhooks': 'notifications/webhooks/creating-webhooks.md'
      - 'Receiving Webhooks': 'notifications/webhooks/receiving.md'
      - 'Configuring TLS/SSL': 'notifications/webhooks/configuring-tls-ssl.md'
    - 'Sample Applications':
      - 'Create SMS Push Notification': 'https://ringcentral-tutorials.github.io/sms-api-nodejs-quickstart/'
      - 'A2P SMS Messaging': 'https://ringcentral-tutorials.github.io/a2p-sms-messaging-nodejs-demo/'

  - 'Downloads and SDKs': sdks.md
  - 'RingCentral Labs': labs.md
